---
title: "Finance 5350 - Final Essay Proposal 'Conflationism'"
author: "Zachary Smith"
date: "October 26, 2018"
output:
  html_document:
    df_print: paged
abstract: Quantifying data to formulate solutions to problems is what economists do to theorize and determine how individuals deal with the allocation of scarce means among alternative competing ends. Since it is impossible to accurately include every individual in data, regressions are run based on whatever data is available and assumptions are made from there. This article will look deeper into the methods economists use to come up with their assumptions and then looks at how using multiple methodologies from multiple schools of thought is a better way to interpret problems since it will involve the individual more. Researching beyond the economist framework by gathering data from different fields of research can give researchers a higher quality N, which will generate data that is less bias and more realistic. 
---



 
## Outline what Buchanan's main point is.


   One of the final quotes In Buchanan's piece is that "learning more about how markets work means learning more about how markets work." Buchan's main point is that economists should be looking at the market without prejudice or bias which is a practical impossibility considering the myriad of facets associated with a constantly changing market. Attempting to come up with problems and finding solutions and equilibriums moves past the idea of understanding the market and only paints a picture of what the market could be. This is just social engineering and does not cover concrete principles of the market based on the voluntary exchange which is entirely individualized making it impossible to be correctly quantified.  
 
## What does Buchanan mean by the word ___catallatics___?
 
  Buchanan is unhappy with the formal definition of economics: "the allocation of scarce means among alternative competing ends." He wants to reclassify this field of research as "catallactic," or "symbiotic." These terms make more sense because they focus on what is mutually beneficial between parties instead of what problems they are faced with due to scarcity. Buchanan does not like that economists look at how are not derived from the market directly, only theoretically because these are assumptions. He calls this the "socially engineered artificial machine." 
 
## According to Buchanan what do most economists do?
 
  Most economists look for a problem and try to quantify a solution. In a free market-based economy, if the market has a problem it will resolve itself uniquely based on what is mutually beneficial to the individual. Economists look beyond the voluntary exchange process and try to come up with a solution that is generalized. This fails to account for the individual who ultimately solves the problem on their own when the market functions properly. Buchanan does not like the idea of trying to solve problems based on computational data: "But I shall continue to insist that our 'purpose,' if you will, is no more that of providing the social engineer with these tools than it is of providing the monopolist with tools to make more profits, or Wicksteed's housewife with the instructions how better to divide out the mashed potatoes among her children. "

## What does he think they should do differently?
 
  Economists should try to look at the market to understand the market rather than do what they generally do, which is gather data based on the market, then try and quantify it computationally. Economists look at what the problems are, then claim to find solutions to the problems with data. The solution to the problem only happens when the market corrects the problem on its own, because it is the mass of individuals within the market that actually make the decisions. Writing about what the solutions are and trying to create theories or policies based on these solutions is not effective or even ethical. "Economists should look at the market with no prejudice or bias towards one form of social order." Only trying to quantify a solution will automatically diminish the important role the individual plays in terms of Adam Smith's, 'invisible hand."
  
## Introduction
  
Buchanan asks What is it economists should do? Economists typically theorize about the allocation of scarce means among alternative competing ends, but Buchanan questions the relevance of this methodology. He points out that "learning more about how markets work means learning more how markets work."  There are several schools of thought on how economic research should be accomplished and there are also several schools of thought on how society can benefit mutually based on the underlying economic principles of the society. Politics tend to aim towards different beliefs based on different theorizations on how the economy works, and the problem tends to be that the individual is never fully accounted for. Hayek argues that using mathematics does not work properly to solve social problems because there cannot be one authority to derive solutions to problems when these problems come from the individual. Ostrom argues that using different fields of research will make for better data collection which is often overlooked in economics. While Buchanan and Hayek take an approach that caters towards the mindset and decision-making process of the individual, Schumpeter looks at how centralized methods of political and economic decision making can be more beneficial to society. This paper will look at how a myriad of methods can be conflated to mitigate the divisive  and incomplete problems that spawn from schools of thought based on finite methodologies. 

## Literature review
  
  One of Adam Smith's key quotes is that "it is the necessary, though very slow and gradual consequence of a certain propensity in human nature which has in view no such extensive utility; the propensity to truck, barter, and exchange one thing for another." He considers his essay to be an essay of persuasion. He disagrees with Robbins statement that, "the allocation of scarce means among alternative competing ends." Instead of looking at economics at characteristics of human activity we look at problems. Economics and society is not only about individual players.
  
  
  People place their own value judgments into their methodology, focusing on exchange rather than choice. Catallactic or symbiotics instead of economics is the preferred term for the field because it is an approach that focuses more on what is mutually beneficial. Solutions to problems happens when the market functions well, not when data is mathematically derived based on assumptions. If the market is viewed as a basis of allocation and the problem element, then the solution becomes generated through an engineered artificial machine-like market which is not representative of the individual. The market is not trying to accomplish anything, only be grounds for voluntary exchange. Buchanan likes the idea of a political constitution, representative of the voluntarist exchange in order to curb the practice of Social Engineerin
 "But I shall continue to insist that our 'purpose,' if you will, is no more that of providing the social engineer with these tools than it is of providing the monopolist with tools to make more profits, or Wicksteed's housewife with the instructions how better to divide out the mashed potatoes among her children. "Economists should look at the market with no prejudice or bias towards one form of social order. "Learning more about how markets work means learning more how markets work. 
 
 
   
  Hayek says, "the calculus in economics does not account for the individual. It's not about access to resources but how to best use resources. Using the same mathematics used to solve natures problems with social problems does not work. Is there to be one authority or are solutions to be derived from the individual? Competition means decentralized planning by many separate persons. Individual decisions are not a science and cannot be centralized and quantified. The method of making knowledge widely available is the problem in need of an answer. It is impossible to come up with an economic plan that can be followed because of time and place evolving. It is easy to overlook small, constant economic changes when viewing an economy through a statistical lens. 
  

    
  Central planning based on statistical information by nature cannot account for the entire sphere of circumstance and will not be precise enough to work for the "man on the Spot" or individual. The individual basis needs on their surroundings and not the reason for why particular choices are available. There is not one person who knows how to make a pencil, and this is the problem with centralized ideology. The marvel of the market response to scarcity. "The problem is precisely how to extend the span of our utilization of resources beyond the span of the control of any one mind." Centralized thinking and solutions removes the ability for the individual to freely use his own knowledge and skill. Hayek argues against the valuation of the factors based on the valuation of consumer goods. Equilibrium analysis often fails to focus on the study of the main problem using any sort of social process
  

    
  Schumpeter says Capitalist reality is unfavorable to maximum performance of production and monopoly has reversed the structures of maximum performance of production. Economists fail to look at the evolution of the economy. The economy is never stationary. The economy in a capitalist market is driven by new methods of production. The economy must be viewed based on how it preforms over long periods of time from decades to centuries. Any analyzation given at only one point in time does not represent the economy. Analyzing a process may give a piece of the process but never more than that. Economist who look at a capital society act like there is no past or future, only looking at the data they have on hand. 
  

  
## Outline

-	Introduction
-	Literature review
-	What economists should be doing
-	Hayek's point of view
-	Schumpeter's point of view
-	Ostrom's view on using multiple methodologies
-	Introduction of the term I made up: Conflationism
-	Is it important to try and fid the solution or to understand the problem?
-	Conclusion

  
 





